### ISSUE TITLE
[PARALLEL-P0] Refuse admission for issues with an exact open PR

### ISSUE THREAD

**Issue by ed3c** [ed3c/noodles#99]
## Goal

Refuse execute admission for any issue that already has an exact open PR, and prove landing stays fail-closed under a race. This is invariant I4 of the N-independent concurrency safety proof; it closes the duplicate-lane class (a ready item with an open PR being re-scheduled into a second attempt) that #46's duplicate-active-branch control cannot catch because a new attempt uses a new branch.

## Dependency and write boundary

- `ed3c/noodles#46` must provider-land, close, and reconcile first; admission mounts in the same execute-admission region.
- Limit changes to the execute admission path, provider readback helpers, and the nearest focused tests.

## Physical acceptance

- Execute admission performs a provider readback of the subject issue; an existing open PR whose head matches the issue's lane naming or whose body references the exact subject fails admission closed, naming the PR, and routes to the repair owner instead of a fresh attempt.
- Planted landing-race regression control: two green candidate lanes over the same base; after the first lands, the second must fail closed to repair (drift/ff-only), never silently merge a stale base.
- Planted open-PR control is rejected at admission; a subject with no open PR is admitted.
- Run focused positive/planted-negative controls, `tests/run.sh`, `./noodles verify`, and readback with zero residue.

## Non-claims

- This does not implement repair itself, close PRs, or replace GitHub strict checks.
- Landing fail-closed already has production evidence (PR #80 drift refusal, #68 ff-only); this atom only pins it with a regression control.
